---
- name: setup host for server
  become: true
  hosts: target_nodes
  remote_user: ansible

  tasks:
    - name: install packages
      import_tasks: ../tasks/install_packages.yml
      vars:
        task_var_pkg: "{{ var_pkgs }}"

    - name: enable services
      import_tasks: ../tasks/enable_and_start_services.yml
      vars:
        task_var_pkg: "{{ var_services }}"


    - name: create server user
      user:
        name: "{{ var_serverr_user }}"
        comment: Standard user to be used to run server
        shell: /bin/bash
        password: "{{ var_serverr_pass }}"
        state: present
        update_password: on_create
        
    - name: create serverr directory
      import_tasks: ../tasks/create_directory.yml
      vars:
        task_var_dir: "{{ var_serverr_dir }}"
        task_var_owner: "{{ var_serverr_user }}"
        task_var_mode: "775"

    - name: set acl permission
      ansible.posix.acl:
        path: "{{ var_serverr_dir }}"
        entity: "{{ var_serverr_user }}"
        etype: user
        permissions: rwx
        state: present
        default: false
        
    - name: set acl default permission
      ansible.posix.acl:
        path: "{{ var_serverr_dir }}"
        entity: "{{ var_serverr_user }}"
        etype: user
        permissions: rwx
        state: present
        default: true
        
    - name: create letsencrypt dir
      import_tasks: ../tasks/create_directory.yml
      vars:
        task_var_dir: "/etc/letsencrypt/live/mokaddimul.com"
        task_var_owner: "root"
        task_var_mode: "755"

    - name: copy certification
      copy:
        src: "../statics/certs/{{ item }}"
        dest: "/etc/letsencrypt/live/mokaddimul.com/{{ item }}"
        owner: root
        group: root
        mode: '0600'
      loop:
        - fullchain.pem
        - privkey.pem
